# ClusterSecretStore — connects ESO to AWS Secrets Manager
# After ESO is installed, all ExternalSecret resources in any namespace
# can reference this store to pull secrets automatically.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
