output "cluster_name"       { value = aws_eks_cluster.this.name }
output "cluster_endpoint"   { value = aws_eks_cluster.this.endpoint }
output "cluster_ca"         { value = aws_eks_cluster.this.certificate_authority[0].data }
output "cluster_version"    { value = aws_eks_cluster.this.version }
output "node_role_arn"      { value = aws_iam_role.node.arn }
output "node_role_name"     { value = aws_iam_role.node.name }
output "oidc_provider_arn"  { value = aws_iam_openid_connect_provider.eks.arn }
output "oidc_provider_url"  { value = replace(aws_iam_openid_connect_provider.eks.url, "https://", "") }
output "cluster_sg_id"      { value = aws_security_group.cluster.id }
